# Generated by Django 5.2.5 on 2025-09-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
