# Generated by Django 5.2.5 on 2025-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('cashier', 'Cashier'), ('chef', 'Chef'), ('waiter', 'Waiter')], default='waiter', max_length=100),
        ),
    ]
