# Generated by Django 5.2.5 on 2025-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_proof',
            new_name='adhar_proof',
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
