# Generated by Django 5.2.5 on 2025-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0013_userphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
    ]
