# Generated by Django 5.2.5 on 2025-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0015_userphoto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
