# Generated by Django 5.2.5 on 2025-09-24 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0017_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
