# Generated by Django 6.0 on 2025-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kot",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COOKING", "Cooking"),
                    ("READY", "Ready"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
