# Generated by Django 6.0 on 2026-02-03 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="userId",
        ),
        migrations.AddField(
            model_name="order",
            name="waiterId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiter_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
