# Generated by Django 5.2.5 on 2025-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
    ]
