# Generated by Django 6.0 on 2026-02-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_order_userid_order_waiterid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kot",
            unique_together={("order", "kot_number")},
        ),
    ]
