# Generated by Django 6.0 on 2025-12-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_kot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kotitem",
            name="items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.menuitem"
            ),
        ),
        migrations.AlterField(
            model_name="kotitem",
            name="kot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="home.kot",
            ),
        ),
    ]
