# Generated by Django 6.0 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_kot_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kot",
            name="kot_number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
