# Generated by Django 5.2.5 on 2025-09-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='floor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.floorname'),
        ),
    ]
