# Generated by Django 6.0 on 2026-02-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_kot_kot_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kot",
            name="kot_number",
            field=models.PositiveIntegerField(),
        ),
    ]
