# Generated by Django 5.2.5 on 2025-09-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_table_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategroy',
            name='table_categroy',
        ),
    ]
