# Generated by Django 5.2.5 on 2025-09-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_menucategroy_table_categroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategroy',
            name='description',
        ),
    ]
