# Generated by Django 6.0 on 2026-02-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_kot_kot_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sent_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
