# Generated by Django 5.2.5 on 2025-09-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_menucategroy_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menucategroy',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='table_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='id_menucategroy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_menucategroy', to='home.menucategroy'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='id_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_table', to='home.table'),
        ),
    ]
