# Generated by Django 6.0 on 2026-02-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_orderitem_sent_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="is_sent_to_kot",
        ),
    ]
