# Generated by Django 6.0 on 2026-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_orderitem_is_sent_to_kot"),
    ]

    operations = [
        migrations.AddField(
            model_name="kot",
            name="is_sent_kot",
            field=models.BooleanField(default=False),
        ),
    ]
