# Generated by Django 5.2.5 on 2025-09-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_menuitem_menucategroy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='id_table',
        ),
    ]
