# Generated by Django 5.2.5 on 2025-09-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_menuitem_id_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='id_menucategroy',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menucategroy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menucategroy', to='home.menucategroy'),
        ),
    ]
