# Generated by Django 6.0 on 2026-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_kot_is_sent_kot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kot",
            name="is_sent_kot",
        ),
        migrations.AddField(
            model_name="kotitem",
            name="is_sent_kot",
            field=models.BooleanField(default=False),
        ),
    ]
