# Generated by Django 5.2.5 on 2025-09-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_menuitem_id_menucategroy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menucategroy',
            new_name='menucategory',
        ),
    ]
