# Generated by Django 6.0 on 2026-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_kot_is_sent_kot_kotitem_is_sent_kot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kot",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
