# Generated by Django 6.0 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_order_notes_alter_kot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kot",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
