# Generated by Django 5.2.5 on 2025-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE IN', 'Dine In'), ('DELIVERY', 'Delivery'), ('PICK UP', 'Pick UP')], default='Dine In', max_length=250),
        ),
    ]
