# Generated by Django 5.2.5 on 2025-09-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
