# Generated by Django 5.2.5 on 2025-09-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_orderitem_order_item_order_orderitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='home.order'),
        ),
    ]
