# Generated by Django 5.2.5 on 2025-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_order_floor_remove_order_orderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
