# Generated by Django 5.2.5 on 2025-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_order',
            new_name='table_orderID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='menu_itemID',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderId',
        ),
    ]
