# Generated by Django 5.2.5 on 2025-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
