# Generated by Django 5.2.5 on 2025-09-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_order_payment_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='order',
        ),
    ]
