# Generated by Django 5.2.5 on 2025-09-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_payment_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_itemID',
            new_name='menu_item',
        ),
    ]
