# Generated by Django 5.2.5 on 2025-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_menu_itemid_orderitem_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='grandTotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table_orderID',
            new_name='tableID',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='itemId',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderId',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('DINE IN', 'Dine In'), ('DELIVERY', 'Delivery'), ('PICK UP', 'Pick UP')], default='DINE IN', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
