# Generated by Django 5.2.5 on 2025-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_total_amount_order_grandtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.IntegerField(default=0),
        ),
    ]
